### ISSUE TITLE
Leaf area wrong in Monserud1999

### ISSUE THREAD

**Issue by RemkoDuursma** [dfalster/baad#226]
By my mistake, used data that I converted to all-surface area, but interpreted as projected area. Leaf areas are too large by a factor of 1.18-1.19 * 2.

**Comment by dfalster** [comment]
Hi Remko, I'm making some fixes to BAAD this week so let me know if this one is easy to fix!

**Comment by RemkoDuursma** [comment]
It is easy to fix. Will do today.
