### ISSUE TITLE
Remove Ecology paper from build

### ISSUE THREAD

**Issue by dfalster** [dfalster/baad#231]
We'll be adding more data to BAAD, which raises the question whether we should retain the ability to build the manuscript published in Ecology in the remake workflow. I'm leaning towards removing it, with instructions in the readme for checking out the appropriate version of the repo for those who want to reproduce the paper. 

Any thoughts @RemkoDuursma @richfitz @dbarneche ?

**Comment by dfalster** [comment]
If we do this then question arises of what we should test to check build worked ok. We could just run remake::make("export") and monitor for errors, or better yet would be to test that the actual output look reasonable. For example, that generates correctly named files, that the files read in as correct types (e.g. list with correct elements, read,csv generates a dataframe without error)

**Comment by RemkoDuursma** [comment]
I think it is fine to remove the code to build the ecology paper. It is unlikely that it is useful to many, and can still be done via a simple checkout anyway. Streamlining seems useful.

**Comment by richfitz** [comment]
I agree with Remko.  There's a version saved in the releases and everything.
